### ISSUE TITLE
[Bug] Character Encoding problem in some tracks’ album tag makes them appear as separate album

### ISSUE THREAD

**Issue by scytho** [zyrouge/symphony#596]
### Description

On some tracks, special characters in the album tag are displayed the wrong way. Those tracks are being shown as a different album in the album view/tab. See attached picture.

### Steps to Reproduce

Unknown. I think I wrote these tags using foobar2000 under wine, so I rewrote the tags and the entire FLAC files with Linux software, which didn’t help. The same files are being handled correctly in the VLC app and the Auxio app.

### Expected Behavior

All characters should be displayed correctly, and all tracks should be in the same album.

### Screenshots

See below.

### Device

-   Device: Google Pixel 6a
-   OS: GrapheneOS (Android 14)
-   Version 2024.3.110

### Additional Context

Could be related to issue #337.

### Checklist

-   [x] I have read the [Contribution Guidelines](https://github.com/zyrouge/symphony/wiki/Contributions-Guidelines#issues).

![symphony_character_encoding_a](https://github.com/user-attachments/assets/8d709cab-8d5d-43a7-ad0d-7d324c08a2b4)

**Comment by vanntile** [comment]
The encoding problems are prevalent, most coming from converting from what I assume to be unicode to a subset of it, but problems with signs/symbols also exist. To list a few problems:
1. `·— —· —· ·· ·` is decoded as `Â·â âÂ· âÂ· Â·Â· Â·`
2. `K/DA` is decoded in the album artist field as `K` and the artist field as `K, DA`, however, the slash problem does not exist in the track or album fields (`POP/STARS` being accurate)
3. `’` in the album and track fields is decoded as `â€™`, while in the artist and album artist fields it is decoded correctly, and differentiated from `'`

**Comment by zyrouge** [comment]
Yeah, this is caused by Android's `MediaStore`, should be fixed when #567 is merged.

**Comment by scytho** [comment]
I am still (or again?) having this issue.

**Comment by scytho** [comment]
I am not sure what the status of this issue is, after #567 and so on. I am on Symphony v2024.12.115 and still having this issue.
